# -*- ruby -*-

# DO NOT EDIT THIS FILE. Instead, edit Rakefile, and run `rake bundler:gemfile`.

source :gemcutter

gem "arel", "~>2.0"

gem "minitest", "~>2.6", :group => [:development, :test]
gem "hoe", "~>2.12", :group => [:development, :test]

# vim: syntax=ruby
